### ISSUE TITLE
Unknown Person

### ISSUE THREAD

**Issue by prakharter** [richmondu/libfaceid#12]
Hi , Thanks for the repo , I am not sure what happens when an untrained person is before the camera  , the model starts predicting someone already trained. It should ideally predict unknown person . 

Also how can i reset a trained model in the folder so that it starts training from scratch , do i need to download a new copy from the repo for that ?

Thanks

**Comment by shree970** [comment]
Which parameters are you using? I did with mtcnn+facenet+knn, gave me false positiives

**Comment by richmondu** [comment]
These stuffs need to be tuned based on the dataset.
There is no one-size fits all face recognition.
Otherwise, Amazon, Google or Microsoft would have release it already.

Tune the parameters based on the datasets, based on how far is the face from the camera, based on the background lighting. I have provided the code. Now, go spread your wings. Dont just download and test. Fine tune based on your conditions. 
Go deeper.
