### ISSUE TITLE
training options

### ISSUE THREAD

**Issue by edurdag** [richmondu/libfaceid#4]
İf you can add train option without align we can try only other options quickly because every train necessary retry align and we loss time,

Other issue program must capture face with realtime from any camera, it's good property for practical test,
 thanks for interesting

**Comment by richmondu** [comment]
İf you can add train option without align we can try only other options quickly because every train necessary retry align and we loss time,
- I don't understand what you mean. facial_recognition_training.py does not do face alignment during training.

Other issue program must capture face with realtime from any camera, it's good property for practical test, thanks for interesting
- yup, will upload soon.
