### ISSUE TITLE
anti-spoofing models

### ISSUE THREAD

**Issue by yaschk** [richmondu/libfaceid#8]
Hi, I tried your colorspace_ycrcbluv_replay.pkl model but it always gives me false results, can you give me advice how to fix it?

**Comment by richmondu** [comment]
Hi Olexander,

The colorspace histogram concatenation model isn’t a good model after testing with different people. It seems to be sensitive with light settings. But you can try adjusting the threshold value to get better prediction. See _threshold_replay in liveness.py. Also I get better result using _print model instead of _replay model.

I’ll try to integrate other models soon. Thanks!

**Comment by synchrony10** [comment]
Hi @richmondu , 

I am currently trying your liveness detection framework but not getting consistent results with replayable videos and hard printed photos. Could you please let me know if you have made further progress with it since your last reply above?

many thanks
